name:  First Workflow
on:  
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a welcome message
        run: echo "Welcome to the first GitHub Action"

      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: List repo
        run: ls -la
