name: Manual Trigger Workflow

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Choose environment to deploy at"
                required: true
                default: "staging"
                type: choice
                options:
                    - staging
                    - production
        

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Deploying App
              run: echo "Deployin App to ${{ inputs.environment }}..." 
                