name: Manual Trigger Workflow

on:
    workflow_dispatch:
        

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: Deploying App
              run: echo "Deployin App..." 
                